/*
 ***********************************************************************
 * CVS Information
 *    $Author$
 *    $Date$
 *    $Revision$
 *    $RCSfile$
 *    $Name$
 ***********************************************************************
 */
/*
 ***********************************************************************
 * Module Name: delay.h                                                *
 *                                                                     * 
 * Purpose: Describes the Macros and Exposes Function Prototypes that  *
 *          will be shared among other modules also                    *
 *                                                                     *  
 * Comments: None                                                      *     
 ***********************************************************************
 */                                                                     
#ifndef _DELAY_H_
#define _DELAY_H_

#define DELAY_TIME 100000  

#define ALLOW_ACCESS 0
#define MAX_RANDOM_ACCESS_VALUES 5

//The Access Value Generated by the
//Randomizing Function
int iAccessValue;

//Seed Initialization Flag
int initSeed;

//Function Prototypes
void delay (void);

#endif
